//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.18 at 01:46:47 PM MSK 
//


package com.example.eximporter.importer.model.xml.product;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="articleTranslation" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="printLanguageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="articleForm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="colorCombination" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="care" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="materialComposition" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="printLanguageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sku" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="skuTranslation" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="printLanguageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="sizeCategoryTranslation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="sizeTranslation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="skuTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="erpSizeKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="skuSequenceNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="qsLength" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="articleTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="articleKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="colorRangeDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="colorGroupDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="purchaseTeamName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="moduleDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="trademarkCareTagDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "articleTranslation",
    "materialComposition",
    "articleFeature",
    "sku"

})
public class Article {

    protected List<ArticleTranslation> articleTranslation;

    @XmlElement(nillable = true)
    protected List<MaterialComposition> materialComposition;

    @XmlElement(nillable = true)
    protected List<ArticleFeature> articleFeature;

    protected List<Sku> sku;
    @XmlAttribute(name = "articleTechId")
    protected String articleTechId;
    @XmlAttribute(name = "articleKey")
    protected String articleKey;
    @XmlAttribute(name = "colorRangeDescription")
    protected String colorRangeDescription;
    @XmlAttribute(name = "colorGroupDescription")
    protected String colorGroupDescription;
    @XmlAttribute(name = "purchaseTeamName")
    protected String purchaseTeamName;
    @XmlAttribute(name = "moduleDescription")
    protected String moduleDescription;
    @XmlAttribute(name = "trademarkCareTagDescription")
    protected String trademarkCareTagDescription;
    @XmlAttribute(name = "trademarks")
    protected String trademarks;


    /**
     * Gets the value of the articleTranslation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articleTranslation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticleTranslation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArticleTranslation }
     * 
     * 
     */
    public List<ArticleTranslation> getArticleTranslation() {
        if (articleTranslation == null) {
            articleTranslation = new ArrayList<>();
        }
        return this.articleTranslation;
    }

    /**
     * Gets the value of the materialComposition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the materialComposition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterialComposition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MaterialComposition }
     * 
     * 
     */
    public List<MaterialComposition> getMaterialComposition() {
        if (materialComposition == null) {
            materialComposition = new ArrayList<>();
        }
        return this.materialComposition;
    }

    /**
     * Gets the value of the sku property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sku property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSku().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sku }
     * 
     * 
     */
    public List<Sku> getSku() {
        if (sku == null) {
            sku = new ArrayList<>();
        }
        return this.sku;
    }

    /**
     * Gets the value of the articleTechId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArticleTechId() {
        return articleTechId;
    }

    /**
     * Sets the value of the articleTechId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArticleTechId(String value) {
        this.articleTechId = value;
    }

    /**
     * Gets the value of the articleKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArticleKey() {
        return articleKey;
    }

    /**
     * Sets the value of the articleKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArticleKey(String value) {
        this.articleKey = value;
    }

    /**
     * Gets the value of the colorRangeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorRangeDescription() {
        return colorRangeDescription;
    }

    /**
     * Gets the value of the colorGroupDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorGroupDescription() {
        return colorGroupDescription;
    }

    public String getPurchaseTeamName() {
        return purchaseTeamName;
    }

    public String getTrademarkCareTagDescription() {
        return trademarkCareTagDescription;
    }

    public void setArticleTranslation(List<ArticleTranslation> articleTranslation)
    {
        this.articleTranslation = articleTranslation;
    }

    public void setMaterialComposition(List<MaterialComposition> materialComposition)
    {
        this.materialComposition = materialComposition;
    }

    public String getModuleDescription() {
        return moduleDescription;
    }

    public String getTrademarks() {
        return trademarks;
    }

    public List<ArticleFeature> getArticleFeature() {
        return articleFeature;
    }

    public void setArticleFeature(List<ArticleFeature> articleFeature) {
        this.articleFeature = articleFeature;
    }
}
