//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.18 at 01:46:47 PM MSK 
//


package com.example.eximporter.importer.model.xml.product;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"value"})
public class ArticleFeature {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "articleFeatureType")
    protected String articleFeatureType;
    @XmlAttribute(name = "articleFeatureId")
    protected String articleFeatureId;

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getArticleFeatureType() {
        return articleFeatureType;
    }

    public String getArticleFeatureId() {
        return articleFeatureId;
    }

}
