//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.18 at 01:46:47 PM MSK 
//


package com.example.eximporter.importer.model.xml.product;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="style" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="article" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="articleTranslation" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="printLanguageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="articleForm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="colorCombination" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="care" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="materialComposition" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="printLanguageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="sku" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="skuTranslation" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="printLanguageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="sizeCategoryTranslation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="sizeTranslation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="skuTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="erpSizeKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="skuSequenceNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="qsLength" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="articleTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="articleKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="colorRangeDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="colorGroupDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="purchaseTeamName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="moduleDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="trademarkCareTagDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="genreAttribute" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="genreAttrName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="genreAttrId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="styleTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="styleKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="wogKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="wogName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="wugKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="wugName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="formType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="exportSequenceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "style"
})
@XmlRootElement(name = "omnArticleExport")
public class OmnArticleExport {

    protected List<Style> style;
    @XmlAttribute(name = "exportSequenceId")
    protected String exportSequenceId;

    /**
     * Gets the value of the style property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the style property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStyle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Style }
     * 
     * 
     */
    public List<Style> getStyle() {
        if (style == null) {
            style = new ArrayList<>();
        }
        return this.style;
    }
}
