//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.18 at 01:46:47 PM MSK
//


package com.example.eximporter.importer.model.xml.product;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="skuTranslation" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="printLanguageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="sizeCategoryTranslation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="sizeTranslation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="skuTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="erpSizeKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="skuSequenceNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="qsLength" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "skuTranslation"
})
public class Sku {

    protected List<SkuTranslation> skuTranslation;
    @XmlAttribute(name = "skuTechId")
    protected String skuTechId;
    @XmlAttribute(name = "erpSizeKey")
    protected String erpSizeKey;
    @XmlAttribute(name = "skuSequenceNum")
    protected String skuSequenceNum;

    @XmlAttribute(name = "sizeTitle")
    protected String sizeTitle;

    @XmlAttribute(name = "recommendedRetailPrice")
    protected String recommendedRetailPrice;


    /**
     * Gets the value of the skuTranslation property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the skuTranslation property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSkuTranslation().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SkuTranslation }
     */
    public List<SkuTranslation> getSkuTranslation() {
        if (skuTranslation == null) {
            skuTranslation = new ArrayList<>();
        }
        return this.skuTranslation;
    }

    /**
     * Gets the value of the skuTechId property.
     *
     * @return possible object is
     *     {@link String }
     */
    public String getSkuTechId() {
        return skuTechId;
    }

    /**
     * Sets the value of the skuTechId property.
     *
     * @param value allowed object is
     *     {@link String }
     */
    public void setSkuTechId(String value) {
        this.skuTechId = value;
    }

    /**
     * Gets the value of the erpSizeKey property.
     *
     * @return possible object is
     *     {@link String }
     */
    public String getErpSizeKey() {
        return erpSizeKey;
    }

    /**
     * Sets the value of the erpSizeKey property.
     *
     * @param value allowed object is
     *     {@link String }
     */
    public void setErpSizeKey(String value) {
        this.erpSizeKey = value;
    }

    /**
     * Gets the value of the skuSequenceNum property.
     *
     * @return possible object is
     *     {@link String }
     */
    public String getSkuSequenceNum() {
        return skuSequenceNum;
    }

    /**
     * Sets the value of the skuSequenceNum property.
     *
     * @param value allowed object is
     *     {@link String }
     */
    public void setSkuSequenceNum(String value) {
        this.skuSequenceNum = value;
    }

    public void setSkuTranslation(List<SkuTranslation> skuTranslation) {
        this.skuTranslation = skuTranslation;
    }

    public String getSizeTitle() {
        return sizeTitle;
    }

    public String getRecommendedRetailPrice() {
        return recommendedRetailPrice;
    }
}
