//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.18 at 01:46:47 PM MSK 
//


package com.example.eximporter.importer.model.xml.product;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="printLanguageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sizeCategoryTranslation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sizeTranslation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class SkuTranslation {

    @XmlAttribute(name = "printLanguageId")
    protected String printLanguageId;
    @XmlAttribute(name = "sizeCategoryTranslation")
    protected String sizeCategoryTranslation;
    @XmlAttribute(name = "sizeTranslation")
    protected String sizeTranslation;
    @XmlAttribute(name = "qsLength")
    protected String qsLength;

    /**
     * Gets the value of the printLanguageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintLanguageId() {
        return printLanguageId;
    }

    /**
     * Sets the value of the printLanguageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintLanguageId(String value) {
        this.printLanguageId = value;
    }

    /**
     * Gets the value of the sizeCategoryTranslation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizeCategoryTranslation() {
        return sizeCategoryTranslation;
    }

    /**
     * Sets the value of the sizeCategoryTranslation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizeCategoryTranslation(String value) {
        this.sizeCategoryTranslation = value;
    }

    /**
     * Gets the value of the sizeTranslation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizeTranslation() {
        return sizeTranslation;
    }

    /**
     * Sets the value of the sizeTranslation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizeTranslation(String value) {
        this.sizeTranslation = value;
    }

    /**
     * Gets the value of the qsLength property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getQsLength() {
        return qsLength;
    }

    /**
     * Sets the value of the qsLength property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setQsLength(String value) {
        this.qsLength = value;
    }
}
