//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.18 at 01:46:47 PM MSK 
//


package com.example.eximporter.importer.model.xml.product;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="article" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="articleTranslation" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="printLanguageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="articleForm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="colorCombination" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="care" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="materialComposition" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="printLanguageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="sku" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="skuTranslation" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="printLanguageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="sizeCategoryTranslation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="sizeTranslation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="skuTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="erpSizeKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="skuSequenceNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="qsLength" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="articleTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="articleKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="colorRangeDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="colorGroupDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="purchaseTeamName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="moduleDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="trademarkCareTagDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="genreAttribute" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="genreAttrName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="genreAttrId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="styleTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="styleKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wogKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wogName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wugKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wugName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="formType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "article",
    "genreAttribute"
})
public class Style {

    protected List<Article> article;
    @XmlElement(nillable = true)
    protected List<GenreAttribute> genreAttribute;
    @XmlAttribute(name = "styleTechId")
    protected String styleTechId;
    @XmlAttribute(name = "styleKey")
    protected String styleKey;
    @XmlAttribute(name = "wogKey")
    protected String wogKey;
    @XmlAttribute(name = "wogName")
    protected String wogName;
    @XmlAttribute(name = "wugKey")
    protected String wugKey;
    @XmlAttribute(name = "wugName")
    protected String wugName;
    @XmlAttribute(name = "formType")
    protected String formType;

    /**
     * Gets the value of the article property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the article property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Article }
     * 
     * 
     */
    public List<Article> getArticle() {
        if (article == null) {
            article = new ArrayList<>();
        }
        return this.article;
    }

    /**
     * Gets the value of the genreAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genreAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenreAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenreAttribute }
     * 
     * 
     */
    public List<GenreAttribute> getGenreAttribute() {
        if (genreAttribute == null) {
            genreAttribute = new ArrayList<>();
        }
        return this.genreAttribute;
    }

    /**
     * Gets the value of the styleTechId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyleTechId() {
        return styleTechId;
    }

    /**
     * Sets the value of the styleTechId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyleTechId(String value) {
        this.styleTechId = value;
    }

    /**
     * Gets the value of the styleKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyleKey() {
        return styleKey;
    }

    /**
     * Sets the value of the styleKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyleKey(String value) {
        this.styleKey = value;
    }

    public String getWogName() {
        return wogName;
    }

    /**
     * Sets the value of the wogName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWogName(String value) {
        this.wogName = value;
    }

    /**
     * Gets the value of the wugName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWugName() {
        return wugName;
    }

    /**
     * Sets the value of the wugName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWugName(String value) {
        this.wugName = value;
    }

    /**
     * Gets the value of the formType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormType() {
        return formType;
    }

    /**
     * Sets the value of the formType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormType(String value) {
        this.formType = value;
    }

    public void setGenreAttribute(List<GenreAttribute> genreAttribute)
    {
        this.genreAttribute = genreAttribute;
    }

    public void setArticle(List<Article> article)
    {
        this.article = article;
    }
}
