//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.16 at 01:05:52 PM MSK 
//


package com.example.eximporter.importer.model.xml.peo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="placement" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="placementSku" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="skuTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="countryIsoCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="advertisedPrice" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="markDownPrice" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="priceReductionRoundedDown" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="priceReduction5PercRounded" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="advertisedPriceDeletedIndicator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="placementTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="articleTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="orderNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="pageKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="pageSlice" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="hasFabricSampleIndicator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="exportSequenceId" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "placement"
})
@XmlRootElement(name = "omnPlacementExport")
public class OmnPlacementExport {

    protected List<Placement> placement;
    @XmlAttribute(name = "exportSequenceId")
    protected Short exportSequenceId;

    /**
     * Gets the value of the placement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the placement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlacement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Placement }
     * 
     * 
     */
    public List<Placement> getPlacement() {
        if (placement == null) {
            placement = new ArrayList<>();
        }
        return this.placement;
    }
}
