//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.18 at 01:57:36 PM MSK 
//


package com.example.eximporter.importer.model.xml.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="admediumPage" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="pageTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="pageKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="workPageNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="admediumVersionId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="exportSequenceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "admediumPage"
})
@XmlRootElement(name = "admediumPageExport")
public class AdmediumPageExport {

    protected List<AdmediumPage> admediumPage;
    @XmlAttribute(name = "exportSequenceId")
    protected String exportSequenceId;

    /**
     * Gets the value of the admediumPage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the admediumPage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdmediumPage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdmediumPage }
     * 
     * 
     */
    public List<AdmediumPage> getAdmediumPage() {
        if (admediumPage == null) {
            admediumPage = new ArrayList<>();
        }
        return this.admediumPage;
    }

}
